version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: maven dependency: go offline
  test:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: mvn package
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
